name: mobile_email_client
description: "android email app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.7.2
dependencies:
  enough_mail: ^2.1.5
  enough_mail_flutter: ^2.1.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  encrypt: ^5.0.1
  sqflite: ^2.4.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
